# Generated by Django 4.2.7 on 2023-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('tipo_seccion', models.CharField(choices=[('general', 'General'), ('interior', 'Interior'), ('exterior', 'Exterior'), ('maquinaria', 'Maquinaria')], default='general', max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('avalible', models.BooleanField(default=True)),
                ('departamento', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
            ],
        ),
    ]
