# Generated by Django 4.2.7 on 2023-12-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_opinion'),
        ('catalogo', '0002_producto_stock'),
    ]

    operations = [
    ]
