# Generated by Django 4.2.7 on 2023-12-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_merge_0002_opinion_0002_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='avalible',
        ),
    ]
