# Generated by Django 4.2.7 on 2023-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_producto_avalible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='comentario',
            field=models.CharField(max_length=255),
        ),
    ]
