# Generated by Django 4.2.7 on 2023-11-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgpi', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
