# Generated by Django 4.2.7 on 2023-11-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgpi', '0003_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
