# Generated by Django 4.2.7 on 2023-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='forma_entrega',
            field=models.CharField(choices=[('Estandar', 'Estandar'), ('Express', 'Express')], default='Estandar', max_length=20),
        ),
    ]
