# Generated by Django 4.2.7 on 2023-12-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='gastos_envio',
            field=models.IntegerField(default=15),
        ),
    ]
