# Generated by Django 4.2.7 on 2023-12-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_carrito_gastos_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='gastos_envio',
        ),
    ]
