# Generated by Django 4.2.7 on 2023-12-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_remove_carrito_gastos_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='gastos_envio',
            field=models.IntegerField(default=0),
        ),
    ]
