# Generated by Django 4.2.7 on 2023-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_remove_carrito_gastos_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='gastos_envio',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True),
        ),
    ]
