# Generated by Django 4.2.7 on 2023-12-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0012_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='num_de_pedido',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
