# Generated by Django 4.2.7 on 2023-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0013_pedido_num_de_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Contra reembolso', 'Contra reembolso')], default='Tarjeta', max_length=20),
        ),
    ]
