# Generated by Django 4.2.7 on 2023-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0015_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='gastos_envio',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=5, null=True),
        ),
    ]
