# Generated by Django 4.2.7 on 2023-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0017_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Contra reembolso', 'Contra reembolso')], default='Tarjeta', max_length=20),
        ),
    ]
