# Generated by Django 4.2.7 on 2023-12-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revisada', 'Revisada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
