# Generated by Django 4.2.7 on 2023-12-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_reclamacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
    ]
